[data]
    name = "Your Name"
    email = "your.email@example.com"
    githubUser = "yourusername"
    editor = "nano"
    defaultShell = "nu"

[diff]
    # Use delta for better diffs if available
    pager = "delta"

[merge]
    # Use your preferred merge tool
    command = "vimdiff"

[edit]
    # Set default editor
    command = "nano"

[git]
    # Enable auto-commit but not auto-push (safer)
    autoCommit = true
    autoPush = false