{{- /* External tools managed by chezmoi */ -}}

# Starship prompt binary
{{- if not (lookPath "starship") }}
[".local/bin/starship"]
    type = "archive-file"
    {{- if eq .chezmoi.os "darwin" }}
        {{- if eq .chezmoi.arch "amd64" }}
    url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-apple-darwin.tar.gz"
        {{- else if eq .chezmoi.arch "arm64" }}
    url = "https://github.com/starship/starship/releases/latest/download/starship-aarch64-apple-darwin.tar.gz"
        {{- end }}
    {{- else if eq .chezmoi.os "linux" }}
        {{- if eq .chezmoi.arch "amd64" }}
    url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"
        {{- else if eq .chezmoi.arch "arm64" }}
    url = "https://github.com/starship/starship/releases/latest/download/starship-aarch64-unknown-linux-gnu.tar.gz"
        {{- else if eq .chezmoi.arch "arm" }}
    url = "https://github.com/starship/starship/releases/latest/download/starship-arm-unknown-linux-gnueabihf.tar.gz"
        {{- end }}
    {{- else if eq .chezmoi.os "windows" }}
        {{- if eq .chezmoi.arch "amd64" }}
    url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-pc-windows-msvc.zip"
        {{- else if eq .chezmoi.arch "arm64" }}
    url = "https://github.com/starship/starship/releases/latest/download/starship-aarch64-pc-windows-msvc.zip"
        {{- end }}
    {{- end }}
    refreshPeriod = "168h"  # Weekly refresh
    executable = true
    stripComponents = 0
    path = "starship{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"
{{- end }}

# bat - A cat clone with syntax highlighting
{{- if not (lookPath "bat") }}
{{- $batAsset := "" -}}
{{- if eq .chezmoi.os "darwin" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $batAsset = "bat-*-x86_64-apple-darwin.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $batAsset = "bat-*-aarch64-apple-darwin.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "linux" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $batAsset = "bat-*-x86_64-unknown-linux-gnu.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $batAsset = "bat-*-aarch64-unknown-linux-gnu.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm" -}}
        {{- $batAsset = "bat-*-arm-unknown-linux-gnueabihf.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "windows" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $batAsset = "bat-*-x86_64-pc-windows-msvc.zip" -}}
    {{- end -}}
{{- end -}}
{{- if $batAsset }}
[".local/bin/bat{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "sharkdp/bat" $batAsset | quote }}
    refreshPeriod = "168h"
    executable = true
    stripComponents = 1
    path = "*/bat{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"
{{- end }}
{{- end }}

# ripgrep - A fast grep alternative
{{- if not (lookPath "rg") }}
{{- $rgAsset := "" -}}
{{- if eq .chezmoi.os "darwin" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $rgAsset = "ripgrep-*-x86_64-apple-darwin.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $rgAsset = "ripgrep-*-aarch64-apple-darwin.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "linux" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $rgAsset = "ripgrep-*-x86_64-unknown-linux-musl.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $rgAsset = "ripgrep-*-aarch64-unknown-linux-musl.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm" -}}
        {{- $rgAsset = "ripgrep-*-arm-unknown-linux-gnueabihf.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "windows" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $rgAsset = "ripgrep-*-x86_64-pc-windows-msvc.zip" -}}
    {{- end -}}
{{- end -}}
{{- if $rgAsset }}
[".local/bin/rg{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "BurntSushi/ripgrep" $rgAsset | quote }}
    refreshPeriod = "168h"
    executable = true
    stripComponents = 1
    path = "*/rg{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"
{{- end }}
{{- end }}

# fd - A simple, fast alternative to find
{{- if not (lookPath "fd") }}
{{- $fdAsset := "" -}}
{{- if eq .chezmoi.os "darwin" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $fdAsset = "fd-*-x86_64-apple-darwin.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $fdAsset = "fd-*-aarch64-apple-darwin.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "linux" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $fdAsset = "fd-*-x86_64-unknown-linux-gnu.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $fdAsset = "fd-*-aarch64-unknown-linux-gnu.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm" -}}
        {{- $fdAsset = "fd-*-arm-unknown-linux-gnueabihf.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "windows" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $fdAsset = "fd-*-x86_64-pc-windows-msvc.zip" -}}
    {{- end -}}
{{- end -}}
{{- if $fdAsset }}
[".local/bin/fd{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "sharkdp/fd" $fdAsset | quote }}
    refreshPeriod = "168h"
    executable = true
    stripComponents = 1
    path = "*/fd{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"
{{- end }}
{{- end }}

# delta - A syntax-highlighting pager for git
{{- if not (lookPath "delta") }}
{{- $deltaAsset := "" -}}
{{- if eq .chezmoi.os "darwin" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $deltaAsset = "delta-*-x86_64-apple-darwin.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $deltaAsset = "delta-*-aarch64-apple-darwin.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "linux" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $deltaAsset = "delta-*-x86_64-unknown-linux-gnu.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $deltaAsset = "delta-*-aarch64-unknown-linux-gnu.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "windows" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $deltaAsset = "delta-*-x86_64-pc-windows-msvc.zip" -}}
    {{- end -}}
{{- end -}}
{{- if $deltaAsset }}
[".local/bin/delta{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "dandavison/delta" $deltaAsset | quote }}
    refreshPeriod = "168h"
    executable = true
    stripComponents = 1
    path = "*/delta{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"
{{- end }}
{{- end }}

# LSD - The next gen ls command
{{- if not (lookPath "lsd") }}
{{- $lsdAsset := "" -}}
{{- if eq .chezmoi.os "darwin" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $lsdAsset = "lsd-*-x86_64-apple-darwin.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $lsdAsset = "lsd-*-aarch64-apple-darwin.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "linux" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $lsdAsset = "lsd-*-x86_64-unknown-linux-gnu.tar.gz" -}}
    {{- else if eq .chezmoi.arch "arm64" -}}
        {{- $lsdAsset = "lsd-*-aarch64-unknown-linux-gnu.tar.gz" -}}
    {{- end -}}
{{- else if eq .chezmoi.os "windows" -}}
    {{- if eq .chezmoi.arch "amd64" -}}
        {{- $lsdAsset = "lsd-*-x86_64-pc-windows-msvc.zip" -}}
    {{- end -}}
{{- end -}}
{{- if $lsdAsset }}
[".local/bin/lsd{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "lsd-rs/lsd" $lsdAsset | quote }}
    refreshPeriod = "168h"
    executable = true
    stripComponents = 1
    path = "*/lsd{{ if eq .chezmoi.os "windows" }}.exe{{ end }}"
{{- end }}
{{- end }}