---
- name: Setup Development Environment
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    # User configuration (mirrors chezmoi config)
    user_name: "{{ ansible_env.USER }}"
    
    # Common PATH entries for all shells
    path_entries:
      - "$HOME/.local/bin"
      - "$HOME/.cargo/bin"
    
    # APT packages to install
    apt_packages:
      - build-essential
      - curl
      - wget
      - git
      - unzip
      - jq
      - htop
      - tree
      - software-properties-common
      - ca-certificates
      - gnupg
      - lsb-release
      - fish
      - ripgrep
      - bat
      - fd-find
    
    # Cargo tools to install
    cargo_tools:
      - name: starship
        binary: starship
      - name: cargo-binstall
        binary: cargo-binstall
      - name: cargo-update
        binary: cargo-install-update
    
    # Additional cargo tools to install via binstall
    cargo_binstall_tools:
      - name: fnm
        binary: fnm
      - name: eza
        binary: eza
      - name: nu
        binary: nu

  tasks:
    # System packages
    - name: Update apt cache and install system packages
      become: yes
      apt:
        name: "{{ apt_packages }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600

    # Symlinks for renamed packages
    - name: Create symlinks for bat and fd
      become: yes
      file:
        src: "/usr/bin/{{ item.src }}"
        dest: "/usr/local/bin/{{ item.dest }}"
        state: link
      loop:
        - { src: 'batcat', dest: 'bat' }
        - { src: 'fdfind', dest: 'fd' }
      ignore_errors: yes

    # Rust installation
    - name: Check if Rust is installed
      command: which cargo
      register: cargo_check
      failed_when: false
      changed_when: false

    - name: Download Rust installer script
      when: cargo_check.rc != 0
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: '0755'
        # Verify HTTPS certificate
        validate_certs: yes
        # Optional: Add checksum verification if Rust provides one
        # checksum: sha256:HASH_HERE

    - name: Verify Rust installer script content
      when: cargo_check.rc != 0
      shell: |
        # Check that it's actually from rust-lang.org
        grep -q "rust-lang.org" /tmp/rustup-init.sh || exit 1
        # Check for expected rustup signatures
        grep -q "rustup" /tmp/rustup-init.sh || exit 1
      register: script_verify

    - name: Install Rust via verified script
      when: cargo_check.rc != 0 and script_verify.rc == 0
      shell: /tmp/rustup-init.sh -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo"

    - name: Clean up installer script
      file:
        path: /tmp/rustup-init.sh
        state: absent

    # Cargo tools installation
    - name: Install cargo tools
      command: "{{ ansible_env.HOME }}/.cargo/bin/cargo install {{ item.name }}"
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item.binary }}"
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
      loop: "{{ cargo_tools }}"

    # Install additional tools via cargo-binstall
    - name: Install tools via cargo-binstall
      command: "{{ ansible_env.HOME }}/.cargo/bin/cargo-binstall -y {{ item.name }}"
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item.binary }}"
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
      loop: "{{ cargo_binstall_tools }}"

    # Create directories
    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ ansible_env.HOME }}/.local/bin"
        - "{{ ansible_env.HOME }}/.config"
        - "{{ ansible_env.HOME }}/.config/fish"
        - "{{ ansible_env.HOME }}/.config/nushell"
        - "{{ ansible_env.HOME }}/.config/ansible_generated"

    # Generate shell configuration snippets
    - name: Generate bash configuration snippet
      template:
        src: templates/common.bash
        dest: "{{ ansible_env.HOME }}/.config/ansible_generated/common.bash"
        mode: '0644'

    - name: Generate fish configuration snippet
      template:
        src: templates/common.fish
        dest: "{{ ansible_env.HOME }}/.config/ansible_generated/common.fish"
        mode: '0644'

    - name: Generate nushell configuration snippet
      template:
        src: templates/common.nu
        dest: "{{ ansible_env.HOME }}/.config/ansible_generated/common.nu"
        mode: '0644'

    # Fonts
    - name: Create fonts directory
      file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory
        mode: '0755'

    - name: Check if JetBrainsMono font is installed
      stat:
        path: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf"
      register: font_check

    - name: Download and install JetBrainsMono Nerd Font
      when: not font_check.stat.exists
      block:
        - name: Download JetBrainsMono Nerd Font
          unarchive:
            src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
            dest: "{{ ansible_env.HOME }}/.local/share/fonts"
            remote_src: yes

        - name: Update font cache
          command: fc-cache -f -v